"""
GPT4All Local LLM Integration
==============================

Local LLM integration using:

    GPT4All
        +
    Qwen2-1.5B-Instruct Q4_0

Task 3:
GPT4All + Gemini + ChromaDB RAG Platform

This module:
1. Locates the locally installed GGUF model.
2. Loads the model through the GPT4All Python SDK.
3. Runs CPU inference.
4. Provides a reusable generate() method.
5. Cleans accidental conversation continuation.
"""

from pathlib import Path

from gpt4all import GPT4All


# ============================================================
# CONFIGURATION
# ============================================================

MODEL_NAME = "qwen2-1_5b-instruct-q4_0.gguf"

MODEL_DIRECTORY = (
    Path.home()
    / "AppData"
    / "Local"
    / "nomic.ai"
    / "GPT4All"
)

MODEL_FILE = MODEL_DIRECTORY / MODEL_NAME


# ============================================================
# GPT4ALL LOCAL LLM
# ============================================================

class GPT4AllLLM:
    """
    Wrapper around the local GPT4All model.
    """

    def __init__(self):

        print("=" * 70)
        print("GPT4ALL LOCAL LLM")
        print("=" * 70)

        print(f"Model: {MODEL_NAME}")
        print(f"Model path: {MODEL_FILE}")

        # ----------------------------------------------------
        # Verify model
        # ----------------------------------------------------

        if not MODEL_FILE.exists():

            raise FileNotFoundError(
                "\nGPT4All model not found.\n\n"
                f"Expected location:\n{MODEL_FILE}\n\n"
                "Please verify that Qwen2-1.5B-Instruct "
                "is installed in GPT4All Desktop."
            )

        print("Model file found.")

        # ----------------------------------------------------
        # Load model
        # ----------------------------------------------------

        print("Loading GPT4All model...")

        self.model = GPT4All(
            model_name=MODEL_NAME,
            model_path=str(MODEL_DIRECTORY),
            allow_download=False,
            device="cpu",
        )

        print("GPT4All model loaded successfully.")

        print("=" * 70)

    # ========================================================
    # GENERATE
    # ========================================================

    def generate(
        self,
        prompt: str,
        max_tokens: int = 400,
        temperature: float = 0.0,
    ) -> str:
        """
        Generate a response from the local LLM.

        Args:
            prompt:
                Prompt sent to the local model.

            max_tokens:
                Maximum number of generated tokens.

            temperature:
                Sampling temperature.
                0.0 is preferred for deterministic
                document-based question answering.

        Returns:
            Clean generated response.
        """

        # ----------------------------------------------------
        # Validate prompt
        # ----------------------------------------------------

        if not prompt or not prompt.strip():

            raise ValueError(
                "Prompt cannot be empty."
            )

        # ----------------------------------------------------
        # Generate response
        # ----------------------------------------------------

        with self.model.chat_session():

            response = self.model.generate(
                prompt,
                max_tokens=max_tokens,
                temp=temperature,
            )

        # ----------------------------------------------------
        # Clean response
        # ----------------------------------------------------

        response = response.strip()

        response = self._clean_response(
            response
        )

        return response

    # ========================================================
    # RESPONSE CLEANING
    # ========================================================

    @staticmethod
    def _clean_response(
        response: str,
    ) -> str:
        """
        Remove accidental conversation continuation
        generated by the local instruction model.
        """

        if not response:
            return ""

        # ----------------------------------------------------
        # End-of-generation markers
        # ----------------------------------------------------

        stop_markers = [
            "<|endoftext|>",
            "<|im_end|>",
            "<|eot_id|>",
            "<|end_of_text|>",
        ]

        # ----------------------------------------------------
        # Conversation continuation markers
        # ----------------------------------------------------

        conversation_markers = [
            "\nHuman:",
            "\nUser:",
            "\nAssistant:",
            "\nSystem:",
        ]

        markers = (
            stop_markers
            + conversation_markers
        )

        # ----------------------------------------------------
        # Keep only the first generated answer
        # ----------------------------------------------------

        earliest_position = None

        for marker in markers:

            position = response.find(
                marker
            )

            if position == -1:
                continue

            if (
                earliest_position is None
                or position < earliest_position
            ):
                earliest_position = position

        if earliest_position is not None:

            response = response[
                :earliest_position
            ]

        return response.strip()


# ============================================================
# SIMPLE TEST
# ============================================================

def main():

    print("=" * 70)
    print("OLLAMA / GPT4ALL LOCAL LLM TEST")
    print("=" * 70)

    # --------------------------------------------------------
    # Load model
    # --------------------------------------------------------

    llm = GPT4AllLLM()

    # --------------------------------------------------------
    # Test question
    # --------------------------------------------------------

    question = (
        "Explain Retrieval Augmented Generation "
        "in simple terms."
    )

    print("\nQuestion:")
    print(question)

    print("\nGenerating response...")

    # --------------------------------------------------------
    # Generate
    # --------------------------------------------------------

    response = llm.generate(
        prompt=question,
        max_tokens=300,
        temperature=0.0,
    )

    # --------------------------------------------------------
    # Display
    # --------------------------------------------------------

    print("\n" + "-" * 70)
    print("GPT4ALL RESPONSE")
    print("-" * 70)

    print(response)

    print("-" * 70)

    print(
        "\nGPT4All test completed successfully."
    )

    print("=" * 70)


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()